version: "3.8"

services:
  landpage:
    image: nginx:alpine
    networks:
      - VIAnalyticsNet
    volumes:
      - /opt/wa-bot-landpage:/usr/share/nginx/html:ro
      - /opt/wa-bot-landpage/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landpage.rule=Host(`whatsapp.vianalytics.com`)"
      - "traefik.http.routers.landpage.entrypoints=websecure"
      - "traefik.http.routers.landpage.tls.certresolver=myresolver"
      - "traefik.http.services.landpage.loadbalancer.server.port=80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  VIAnalyticsNet:
    external: true