version: "3.8"

services:
  landpage:
    image: nginx:latest
    container_name: nginx_landpage
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - VIAnalyticsNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landpage.rule=Host(`whatsapp.vianalytics.tech`)"
      - "traefik.http.routers.landpage.entrypoints=websecure"
      - "traefik.http.routers.landpage.tls.certresolver=letsencrypt"
      - "traefik.http.services.landpage.loadbalancer.server.port=80"

networks:
  VIAnalyticsNet:
    external: true