version: "3.8"

services:
  landpage:
    image: nginx:latest
    container_name: nginx_landpage
    restart: always
    volumes:
      - ./landpage:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landpage.rule=Host(`whatsapp.vianalytics.tech`)"
      - "traefik.http.routers.landpage.entrypoints=websecure"
      - "traefik.http.routers.landpage.tls.certresolver=letsencrypt"
      - "traefik.http.services.landpage.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Optional Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik_network

networks:
  traefik_network:
    driver: bridge